module.exports = {
  purge: [],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      backgroundColor: {
        'black': '#111',
        'transparent': '#FF000000',
        'matteBlack': '#1B1B1B',
        'white': '#ffffff',
        'dirty-white': '#edebe4',
        'mattePurple': '#392A48',
        'matteBlue': '#7AAEC4',
        'matteGreen': '#48A14D',
        'matteYellow': '#EDD94C',
        'matteOrange': '#ED944D',
        'matteRed': '#B33F40',
        'copperRose': '#9d5c63',
        'darkliver': '#584b53',
        'dessertsand': '#e4bb97',
        'seashell': '#fef5ef',
        'periwinkle': '#d6e3f8',
        'burntsienna': '#ee6c4d',
        'darksalmon': '#f38d68',
        'rebeccapurple': '#662c91',
        'persiangreen': '#17a398',
        'jet': '#33312e',
        'grey' : '#777',
        'pink' : '#FF1E56',
        'peach' : '#FFAC41'
      },
      textColor: {
        'black': '#111',
        'matteBlack': '#1B1B1B',
        'white': '#ffffff',
        'danger': '#e3342f',
        'mattePurple': '#392A48',
        'matteBlue': '#7AAEC4',
        'matteGreen': '#48A14D',
        'matteYellow': '#EDD94C',
        'matteOrange': '#ED944D',
        'matteRed': '#B33F40',
        'copperRose': '#9d5c63',
        'darkliver': '#584b53',
        'dessertsand': '#e4bb97',
        'seashell': '#fef5ef',
        'periwinkle': '#d6e3f8',
        'burntsienna': '#ee6c4d',
        'darksalmon': '#f38d68',
        'rebeccapurple': '#662c91',
        'persiangreen': '#17a398',
        'jet': '#33312e',
        'grey' : '#777',
        'pink' : '#FF1E56',
        'peach' : '#FFAC41'


      },
      width: {
        '.10': '10%',
        '.20': '20%',
        '.30': '30%',
        '.40': '40%',
        '.45': '45%',
        '.50': '50%',
        '.55': '55%',
        '.60': '60%',
        '.70': '70%',
        '.80': '80%',
        '.90': '90%',
        '.100': '100%',
      },
      height: {
        '.10': '10%',
        '.20': '20%',
        '.30': '30%',
        '.40': '40%',
        '.45': '45%',
        '.50': '50%',
        '.55': '55%',
        '.60': '60%',
        '.70': '70%',
        '.80': '80%',
        '.90': '90%',
        '.100': '100%',
      },
      fontSize: {
        '.1': '10%',
        '.2': '20%',
        '.3': '30%',
        '.4': '40%',
        '.5': '50%',
        '.6': '60%',
        '.7': '70%',
        '.8': '80%',
        '.9': '90%',
        '.10': '100%',
      },
      inset: {
        '.35': '35%',
        '.40': '40%',
      }


    },
    fontFamily: {
      body: ['Poppins']
    },
  },
  variants: {
    extend: {
      borderWidth: ['hover', 'focus'],
      top: ['hover', 'focus', 'group-hover'],
      bottom: ['hover', 'focus'],
      left: ['hover', 'focus'],
      right: ['hover', 'focus', 'group-hover'],
      inset: ['hover', 'focus', 'group-hover'],
      transform: ['responsive', 'dark', 'group-hover', 'focus-within', 'hover', 'focus',],
      transformOrigin: ['responsive', 'dark', 'group-hover', 'focus-within', 'hover', 'focus'],
      transitionDelay: ['responsive', 'dark', 'group-hover', 'focus-within', 'hover', 'focus'],
      transitionDuration: ['responsive', 'dark', 'group-hover', 'focus-within', 'hover', 'focus'],
      transitionProperty: ['responsive', 'dark', 'group-hover', 'focus-within', 'hover', 'focus'],
      transitionTimingFunction: ['responsive', 'dark', 'group-hover', 'focus-within', 'hover', 'focus'],
      transition: ['responsive', 'dark', 'group-hover', 'focus-within', 'hover', 'focus'],
      translate: ['responsive', 'dark', 'group-hover', 'focus-within', 'hover', 'focus'],
      animation: ['hover', 'focus', 'group-hover'],
      display: ['hover', , 'focus', 'group-hover'],
      fontSize: ['hover', 'focus'],
      position: ['hover', 'focus'],

    },
  },
  plugins: [],
}
